field: c9f8a280-0c30-494c-80eb-db78eb439064 # Content Modules
fieldLayouts:
  91bd8232-3507-4d3b-9a9a-c98b219d0a75:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 94452cfe-48ba-4aee-a1f6-3f34f087db4d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8eff24f8-6bda-4cd1-baf1-89077c6eec5f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 56ad6d80-7299-4290-99b3-43ed585679f4 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 534addd6-ca45-409e-bf3d-b56adc8dd224
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 52d198b4-25f1-4832-a440-e0741c9bac18 # Foreground Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8bf0cd8f-cacc-4cbd-9cae-a76c25098607
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: da5d8cd3-25fa-4cb7-8d0d-3c3f8d63de90 # Background Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7616152-afd2-4de3-9f30-e9a66b4c071e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a702eb0a-6d08-4038-b5f4-ba5dc3771426 # Radiant Circles
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61cf1890-b503-4449-9434-f61c57a2ffa3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f2c0ddd1-a1fe-4017-adef-ebf9b23e04b5 # Benefits
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a22c6371-2fb9-4449-a12a-918bae66d789
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d1d24d4-2b07-49db-9d74-8d22b32059a8 # Module
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0561f6d-c4b3-404c-a9bc-2b461ec711ab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5bcf5ba5-1c8d-466b-8ddf-3b7f14dd1383
        userCondition: null
fields:
  9d1d24d4-2b07-49db-9d74-8d22b32059a8: # Module
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: module
    instructions: "Use this field to control layout options for this module. Click `Module Settings` to reveal the settings.\r\n\r\nProviding a custom ID allows for the creation of custom jump links. IDs must start with a letter, must only contain alphanumeric characters, hyphens and dashes. They are limited to 48 characters."
    name: Module
    searchable: false
    settings:
      backgrounds:
        - white
        - light
        - transparent
      backgroundsDefault: light
      decorations:
        - borderTop
        - borderBottom
      decorationsDefault: ''
      independentPadding: ''
      moduleId: ''
      overflow:
        - hidden
        - visible
      padding:
        - none
        - small
        - medium
        - large
      paddingDefault: medium
    translationKeyFormat: null
    translationMethod: none
    type: modules\ccfieldsmodule\fields\Module
  52d198b4-25f1-4832-a440-e0741c9bac18: # Foreground Media
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: fgMedia
    instructions: "Use this field to define the media to be rendered next to the list of benefits. This will display on top of the Background Media. This field allows selections from the following asset volumes:\r\n\r\n* Images"
    name: 'Foreground Media'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:b58b753c-d44b-4f17-9895-3819a449c7d3' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:b58b753c-d44b-4f17-9895-3819a449c7d3' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add foreground media'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:b58b753c-d44b-4f17-9895-3819a449c7d3' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  56ad6d80-7299-4290-99b3-43ed585679f4: # Content
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: contentText
    instructions: 'Use this field to add introductory content for this module.'
    name: Content
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      blockTypeBehaviour: click
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      defaultUploadLocationSource: 'volume:b58b753c-d44b-4f17-9895-3819a449c7d3' # Images
      editorMode: combined
      initialRows: 7
      manualConfig: ''
      maxBlocks: null
      minBlocks: null
      pasteAsPlainText: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      trimEmptyParagraphs: true
      vizyConfig: Simple.json
    translationKeyFormat: null
    translationMethod: none
    type: verbb\vizy\fields\VizyField
  94452cfe-48ba-4aee-a1f6-3f34f087db4d: # Heading
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: heading
    instructions: "Use this field to add a heading to this module.\r\n\r\nTo highlight a particular piece of the heading text, wrap the targeted words in single asterisk (`*`). For example: `this is a *highlighted* heading`.\r\n\r\nThis field also allows you to set the heading level. _Please use this feature with caution and ensure proper document structure,_ as improper document structures are an accessibility concern. "
    name: Heading
    searchable: true
    settings:
      defaults:
        __assoc__:
          -
            - levels
            -
              __assoc__:
                -
                  - h1
                  - H1
                -
                  - h2
                  - H2
                -
                  - h3
                  - H3
                -
                  - h4
                  - H4
          -
            - sizing
            -
              __assoc__:
                -
                  - default
                  - Default
                -
                  - h1
                  - H1
                -
                  - h2
                  - H2
                -
                  - h3
                  - H3
                -
                  - h4
                  - H4
                -
                  - h5
                  - H5
      heading: ''
      levelDefault: h2
      levels:
        - h2
      sizing:
        - h1
        - h2
        - h3
        - h4
      sizingDefault: h2
    translationKeyFormat: null
    translationMethod: none
    type: modules\ccfieldsmodule\fields\Heading
  a702eb0a-6d08-4038-b5f4-ba5dc3771426: # Radiant Circles
    columnSuffix: hnqibfeq
    contentColumnType: boolean
    fieldGroup: null
    handle: radiantCircles
    instructions: 'Use this field to toggle the display of the radiant circles decoration.'
    name: 'Radiant Circles'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  da5d8cd3-25fa-4cb7-8d0d-3c3f8d63de90: # Background Media
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: bgMedia
    instructions: "Use this field to define the background media to be rendered next to the list of benefits. This will display behind the Foreground Media. This field allows selections from the following asset volumes:\r\n\r\n* Images"
    name: 'Background Media'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:b58b753c-d44b-4f17-9895-3819a449c7d3' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:b58b753c-d44b-4f17-9895-3819a449c7d3' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add background media'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:b58b753c-d44b-4f17-9895-3819a449c7d3' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f2c0ddd1-a1fe-4017-adef-ebf9b23e04b5: # Benefits
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: benefits
    instructions: 'Use this field to select or create a Product Benefit entry.'
    name: Benefits
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: 'Add a benefit'
      showSiteMenu: true
      sources:
        - 'section:db611318-a807-435d-8e9a-40a059d79429' # Product Benefits
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: benefits
name: Benefits
sortOrder: 2
