field: e90d0415-a93d-444d-80bb-836c952c6cc9 # Button
fieldLayouts:
  8a23b8a4-f832-4830-8437-2b631451ac35:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 228b3771-6166-4c1f-9799-c00a4acb5ac4 # Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a663590b-f65a-42e1-98ef-ea2444c3cb3a
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: abbdd14f-37e4-4070-9898-9b16bfbf6caa # Button Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7606e55b-7b5d-4d94-b837-b5adae65311c
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 0eb0dd20-35fa-4e1d-9c9d-0c2a26559b0c
        userCondition: null
fields:
  228b3771-6166-4c1f-9799-c00a4acb5ac4: # Button Link
    columnSuffix: fnzzmgub
    contentColumnType: string
    fieldGroup: null
    handle: buttonLink
    instructions: null
    name: 'Button Link'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: asset
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        craftCommerce-product:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources:
            - 'productType:f94ef620-73da-4c8a-a57b-a45a1fc6a717' # Probiotics
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: true
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources:
            - singles
            - 'section:3b1d5657-f4f2-42df-ad71-e8eec665b105' # Blog
            - 'section:6f418409-f60c-4dcb-9e0e-c78b08721a12' # Recipe
            - 'section:43d82d49-59c5-402b-85a6-b009c84626c8' # Pages
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: true
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  abbdd14f-37e4-4070-9898-9b16bfbf6caa: # Button Style
    columnSuffix: bagjrtwu
    contentColumnType: string
    fieldGroup: null
    handle: buttonStyle
    instructions: null
    name: 'Button Style'
    searchable: false
    settings:
      newLabelFormat: '{{ label }}'
      options:
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - primary
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - secondary
        -
          __assoc__:
            -
              - label
              - Terracotta
            -
              - value
              - terracotta
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - white
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - large
      sourceGlobal: buttonStyle
      sourceLabelHandle: label
      sourceValueHandle: value
    translationKeyFormat: null
    translationMethod: none
    type: modules\ccfieldsmodule\fields\PresetDropdown
handle: button
name: Button
sortOrder: 1
