field: c9f8a280-0c30-494c-80eb-db78eb439064 # Content Modules
fieldLayouts:
  6072280d-c6dc-4365-8f7a-29287c887792:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c2ba9be4-065f-42b3-a293-377ac52af252 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad8420f0-386e-44d5-bd7a-780c79a62f0c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5eec94af-2a5f-4210-9df2-6affa3c1a6ed # Text Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96b2f062-b692-4267-9bb7-782f9fc05242
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54a3c05b-2ff1-41a1-ac01-cc2f02150db3 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9244e2e-2fdb-4b48-88b2-4855b553ad32
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8fa5b4f5-0dba-4403-b6f7-883613510a7d # Products
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ffa787b-4b9b-4ee9-a2c7-e05944d203df
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55636913-b4d9-4664-8a84-063fad308780 # Module
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2dca9bd7-697d-4a50-9dd4-12922f3878f1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 508c645b-113a-4593-9268-bea90f8744a0
        userCondition: null
fields:
  5eec94af-2a5f-4210-9df2-6affa3c1a6ed: # Text Content
    columnSuffix: cqcjyzch
    contentColumnType: string(800)
    fieldGroup: null
    handle: textContent
    instructions: 'Use this field to add introductory content for this module.'
    name: 'Text Content'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 200
      code: false
      columnType: null
      initialRows: 2
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8fa5b4f5-0dba-4403-b6f7-883613510a7d: # Products
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: products
    instructions: 'Use this field to select up to 2 related products.'
    name: Products
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 2
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\commerce\fields\Products
  54a3c05b-2ff1-41a1-ac01-cc2f02150db3: # Button
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: button
    instructions: 'Use this field to define the optional button for this module.'
    name: Button
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 100
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        craftCommerce-product:
          allowCrossSiteLink: false
          allowCustomQuery: true
          enabled: true
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: true
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: true
          enabled: true
          sources:
            - singles
            - 'section:3b1d5657-f4f2-42df-ad71-e8eec665b105' # Blog
            - 'section:6f418409-f60c-4dcb-9e0e-c78b08721a12' # Recipe
            - 'section:43d82d49-59c5-402b-85a6-b009c84626c8' # Pages
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: true
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  55636913-b4d9-4664-8a84-063fad308780: # Module
    columnSuffix: vahtokxs
    contentColumnType: string
    fieldGroup: null
    handle: module
    instructions: "Use this field to control layout options for this module. Click `Module Settings` to reveal the settings.\r\n\r\nProviding a custom ID allows for the creation of custom jump links. IDs must start with a letter, must only contain alphanumeric characters, hyphens and dashes. They are limited to 48 characters."
    name: Module
    searchable: false
    settings:
      backgrounds:
        - white
        - light
      backgroundsDefault: light
      decorations:
        - brushBottom
      decorationsDefault: ''
      independentPadding: '1'
      moduleId: ''
      overflow: ''
      padding:
        - none
        - small
        - medium
        - large
      paddingDefault: medium
    translationKeyFormat: null
    translationMethod: none
    type: modules\ccfieldsmodule\fields\Module
  c2ba9be4-065f-42b3-a293-377ac52af252: # Heading
    columnSuffix: ngpljrjz
    contentColumnType: string
    fieldGroup: null
    handle: heading
    instructions: "Use this field to add a heading to this module.\r\n\r\nTo highlight a particular piece of the heading text, wrap the targeted words in single asterisk (`*`). For example: `this is a *highlighted* heading`.\r\n\r\nThis field also allows you to set the heading level. _Please use this feature with caution and ensure proper document structure,_ as improper document structures are an accessibility concern. "
    name: Heading
    searchable: false
    settings:
      defaults:
        __assoc__:
          -
            - levels
            -
              __assoc__:
                -
                  - h1
                  - H1
                -
                  - h2
                  - H2
                -
                  - h3
                  - H3
                -
                  - h4
                  - H4
          -
            - sizing
            -
              __assoc__:
                -
                  - default
                  - Default
                -
                  - h1
                  - H1
                -
                  - h2
                  - H2
                -
                  - h3
                  - H3
                -
                  - h4
                  - H4
                -
                  - h5
                  - H5
      heading: ''
      levelDefault: h2
      levels:
        - h2
        - h3
      sizing:
        - h1
        - h2
        - h3
        - h4
      sizingDefault: h2
    translationKeyFormat: null
    translationMethod: none
    type: modules\ccfieldsmodule\fields\Heading
handle: relatedProducts
name: 'Related Products'
sortOrder: 13
