fieldLayouts:
  9333e8f9-92d3-4cd5-ab93-3ffeecf22b86:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ecb6c561-25ed-44be-9301-2f5b9fa2094b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1262417d-adab-4273-9f2b-02709eae6778 # Site Header Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e29256c-3b1f-437e-bd05-023b31da0201
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 849814e4-c9bf-4019-94d3-d8ad5ba06f16 # Background Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fd71c7b-bfa5-46cc-9192-82021c5024cf
            userCondition: null
            warning: null
            width: 100
        name: Header
        uid: 75dbe7ac-9d15-46d5-8da1-12ffe7b7270c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d3bfabb5-8866-4800-b96c-5f27d67a7676 # Checkout Step
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea25dbcc-4670-4e98-b6b0-96722ff77ead
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\LineBreak
            uid: b26c6d90-4501-4645-928f-d4d5330d252d
            userCondition: null
          -
            elementCondition: null
            fieldUid: c8b0755e-8212-4a0a-9b4d-97401085e0e7 # Checkout Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50db8d17-06e5-49df-ae44-c761a9a521a4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 2baf79f3-8a6d-4ba5-baa2-ebecf707d81a # Checkout Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9268279-b4a0-43fa-9a50-a3b0074efc27
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e7cd43f6-8044-438e-9024-93d73c55c158
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7fc3fc05-0137-49b6-8d71-ab23acbb9122 # Form Submission Redirect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdb3f0e4-9e9b-4853-86f3-f7594572a965
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d38dd7f6-5fb4-4952-8afe-daec2d3137c6 # Subscription Redirect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a9cb584-3709-41c6-b791-e5d8076a73da
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 60f2ea8e-952b-4494-831b-188c6fc1647f # Form Submit Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4fa1e28f-6f94-400e-83be-48b9b2a03a0d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\LineBreak
            uid: eeb58041-8460-4296-8216-f7815f62f176
            userCondition: null
          -
            elementCondition: null
            fieldUid: 4c902f96-ee5e-48b0-97f8-433efb8726e9 # Form Success Message
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ff5e467-0783-4793-b247-e9036f5b265a
            userCondition: null
            warning: null
            width: 50
        name: Form
        uid: 1b569e8c-1141-4e6c-a1e3-1607f085205f
        userCondition: null
handle: checkoutPaymentMethod
hasTitleField: true
name: 'Checkout Payment Method'
section: a8188730-d041-4b1c-91c1-19fba1e60b19 # Checkout
sortOrder: 6
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
