defaultPlacement: end
fieldLayouts:
  4c4c092e-11ce-4b2c-bc7a-e747cdd7f8f3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 939d57c7-91c5-41dc-92f0-b3e70f1fcaa6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ceaebd43-e55a-4cc7-8826-2975bcb52741 # Link Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09828bb0-1fe6-4d32-90ed-638b45d43d72
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 9d771f45-bec9-4002-b990-0a0402ced930
            userCondition: null
            warning: null
          -
            attribute: newWindow
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: 930d3caa-1ebf-4463-b156-71821d21a37f
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: 8a1ee448-8c80-49b2-b144-12768900f912
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 0d92dcbe-ee27-48a8-80bb-442da5ae8785
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: a5a74b68-530e-4f9d-968a-a3099052fd96
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: ce9a5790-ba87-4454-9fe5-efa3acff4e1c
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 51389f05-7a0e-47dd-8505-137a6701efeb
        userCondition: null
handle: footerNavigation
instructions: null
maxNodes: null
name: 'Footer Navigation'
permissions:
  craft\commerce\elements\Product:
    enabled: '1'
    permissions: '*'
  craft\elements\Asset:
    enabled: ''
    permissions: '*'
  craft\elements\Category:
    enabled: ''
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: all
siteSettings:
  da016506-9b96-43e4-9e38-d4c30ec3294c: # Olina
    enabled: true
sortOrder: 3
structure:
  maxLevels: null
  uid: 28afe87a-d7d1-48f2-83a4-0b9aa5da65ca
