defaultPlacement: end
fieldLayouts:
  5898ff81-9f48-452f-91a3-82dd0125bc91:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 6bbc82c3-be02-4229-8f38-977097428421
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: d54b25f4-b7d3-44ef-8d30-107aa5b1b02c
            userCondition: null
            warning: null
        name: Content
        uid: 706bb8bc-b690-453f-9d06-2eb0e736edb9
        userCondition: null
handle: primaryNavigation
instructions: null
maxNodes: null
name: 'Primary Navigation'
permissions:
  craft\elements\Asset:
    enabled: ''
    permissions: '*'
  craft\elements\Category:
    enabled: ''
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: none
siteSettings:
  da016506-9b96-43e4-9e38-d4c30ec3294c: # Olina
    enabled: true
sortOrder: 2
structure:
  maxLevels: null
  uid: cf845658-4d9b-4ce2-bc4c-bc6565fb91e3
