defaultPlacement: end
fieldLayouts:
  5824ac56-e802-4d49-a4b2-2012adec3289:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 6622ad2d-c982-4dc8-b554-2d0eb90f18da
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 98805853-186c-436c-9783-56bfe13ba450
            userCondition: null
            warning: null
          -
            attribute: newWindow
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: 0a791bb5-238d-4ff0-bd51-3fcc63b057e7
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: 848cb439-55f8-4607-af3b-428a096b9977
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: b9e0e54a-5a01-4a3d-8311-3dab224fb671
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: 7618eca1-b5cd-4244-bd33-3540f09b94e7
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: 0088ceaa-6c31-48e0-8a27-4941ecd5411f
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 3139a205-029d-4e21-9c6c-511972e8b77d
        userCondition: null
handle: userNavigation
instructions: null
maxNodes: null
name: 'User Navigation'
permissions:
  craft\commerce\elements\Product:
    enabled: ''
    permissions: '*'
  craft\elements\Asset:
    enabled: ''
    permissions: '*'
  craft\elements\Category:
    enabled: ''
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: none
siteSettings:
  da016506-9b96-43e4-9e38-d4c30ec3294c: # Olina
    enabled: true
sortOrder: 5
structure:
  maxLevels: 1
  uid: faa2a02a-018b-4652-9705-4016d1c597e3
