tabs:
  -
    elementCondition: null
    elements:
      -
        attribute: addresses
        elementCondition: null
        id: null
        instructions: null
        label: null
        orientation: null
        requirable: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\users\AddressesField
        uid: 6f6d67f4-8ffa-4499-bd27-1ca7295116f0
        userCondition: null
        warning: null
        width: 100
    name: Addresses
    uid: f19e742f-3af3-4b50-a2d2-d4602aa9406c
    userCondition: null
