fieldLayouts:
  f0d3a167-d6ed-4ce2-a572-59d9db153ee0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 996ef981-48ab-4726-9429-e903d5886feb
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: c9d48f16-2a56-4422-9095-d38526b7d5fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1cd4213c-748a-4b0c-8e49-5d01457b3efa # Media Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5b8239a-02f2-4831-a6ff-21c74552dd13
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3513fc7a-8d0e-44dd-8ca8-5a76df4cb4ae
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: images
