fieldLayouts:
  d2be02d6-2c96-434c-b3e1-6530b78c797b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 8b9f7cc0-6921-4b66-8637-fbf5d20369a8
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 21caa623-24b8-48db-8a48-80142541f9f9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e336f44-41a0-4694-98e4-225eec21d73c # Video Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 257333bb-3c24-4385-bf8d-5441cc48686c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 360e633b-8ece-4eb3-90db-8044b967f111 # Video ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85878402-396b-4330-be3f-b2ac4bfdc5ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7b2fcf17-543b-43a1-8571-ddf266d2539c # Video Transcript
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b770b5f-4e7c-4763-b655-130d1e9a3b49
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 09439a49-78c4-4d5d-8583-1d238b4792a5
        userCondition: null
fs: videos
handle: videos
name: 'Videos External'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: videos
