columnSuffix: qgvzdvcg
contentColumnType: string
fieldGroup: 05ae0857-ee4f-45f0-b0af-6ae648cd7caa # Avatax
handle: avataxCustomerUsageType
instructions: 'Select an [Entity/Use Code](https://help.avalara.com/000_Avalara_AvaTax/Exemption_Reason_Matrices_for_US_and_Canada) to exempt this customer from tax.'
name: 'AvaTax Customer Usage Type'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - ''
        -
          - value
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'A. Federal government (United States)'
        -
          - value
          - A
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'B. State government (United States)'
        -
          - value
          - B
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'C. Tribe / Status Indian / Indian Band (both)'
        -
          - value
          - C
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'D. Foreign diplomat (both)'
        -
          - value
          - D
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'E. Charitable or benevolent org (both)'
        -
          - value
          - E
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'F. Religious or educational org (both)'
        -
          - value
          - F
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'G. Resale (both)'
        -
          - value
          - G
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'H. Commercial agricultural production (both)'
        -
          - value
          - H
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'I. Industrial production / manufacturer (both)'
        -
          - value
          - I
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'J. Direct pay permit (United States)'
        -
          - value
          - J
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'K. Direct mail (United States)'
        -
          - value
          - K
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'L. Other (both)'
        -
          - value
          - L
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'M. Not Used'
        -
          - value
          - M
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'N. Local government (United States)'
        -
          - value
          - 'N'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'O. Not Used'
        -
          - value
          - O
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'P. Commercial aquaculture (Canada)'
        -
          - value
          - P
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Q. Commercial Fishery (Canada)'
        -
          - value
          - Q
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'R. Non-resident (Canada)'
        -
          - value
          - R
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
