columnSuffix: anhwcjhd
contentColumnType: text
fieldGroup: 05ae0857-ee4f-45f0-b0af-6ae648cd7caa # Avatax
handle: avataxTaxCode
instructions: 'Specify an [Avalara Tax Code](https://taxcode.avatax.avalara.com) to use for this product.'
name: 'AvaTax Tax Code'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
