columnSuffix: fbpibose
contentColumnType: text
fieldGroup: e54d5633-67e4-4147-ac0a-daecea3240dc # Review
handle: ctaHeadingGuest
instructions: 'Use this field to enter text for the CTA heading for a logged in user.'
name: 'CTA Heading (Guest)'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
