columnSuffix: adbljuay
contentColumnType: text
fieldGroup: a952bf2b-b44b-4581-bf77-5a1b7d885121 # User
handle: forgotPasswordHeading
instructions: 'Use this field to enter a heading to display at the top of the Forgot Password form.'
name: 'Forgot Password Heading'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
