columnSuffix: tdoweuat
contentColumnType: text
fieldGroup: 1901e8d3-2a7e-47ef-94ec-a27c6f4346e2 # Header
handle: heading
instructions: "Use this field to add a custom heading to this entry. If this field is left blank the value of the `Title` field will be used instead.\r\n\r\nTo highlight a particular piece of the heading text, wrap the targeted words in single asterisk (`*`). For example: `this is a *highlighted* heading`."
name: Heading
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
