columnSuffix: gpoyrqoy
contentColumnType: text
fieldGroup: a952bf2b-b44b-4581-bf77-5a1b7d885121 # User
handle: passwordSetText
instructions: 'Use this field to enter text to appear above the password set form.'
name: 'Password Set Text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  initialRows: 7
  manualConfig: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  trimEmptyParagraphs: true
  vizyConfig: Simple.json
translationKeyFormat: null
translationMethod: none
type: verbb\vizy\fields\VizyField
