columnSuffix: lwfuzxmo
contentColumnType: text
fieldGroup: 3f0bc8e2-2e90-4b58-be74-00243d9b4a9e # SEO
handle: seoSettings
instructions: 'Use this field to override global SEOmatic settings per entry.'
name: 'SEO Settings'
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields: ''
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoTitle
    - seoDescription
    - seoKeywords
    - seoImage
    - robots
  generalTabEnabled: '1'
  sitemapEnabledFields: ''
  sitemapTabEnabled: ''
  twitterEnabledFields: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
