columnSuffix: null
contentColumnType: string
fieldGroup: a952bf2b-b44b-4581-bf77-5a1b7d885121 # User
handle: subscription
instructions: null
name: Subscription
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:601faa45-0a91-48f9-8a35-9e2e4967cdc2' # Subscription Plan Details
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
