columnSuffix: null
contentColumnType: string
fieldGroup: d1d877d6-8695-4cbb-8eda-fa0a9e729c90 # Author
handle: videoFileSecondary
instructions: "Use this field to upload a secondary video source.\r\n\r\nBy adding in a second video source in .ogg or .webm in your code you can avoid almost all issues. Both options are fairly equally supported in different desktop browsers."
name: 'Video File Secondary'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:04fe8547-3f55-4da7-b1a5-7b70c1c933d2' # Video Files
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:b58b753c-d44b-4f17-9895-3819a449c7d3' # Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: 'Add a secondary video file'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:04fe8547-3f55-4da7-b1a5-7b70c1c933d2' # Video Files
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
