changedFieldIndicator: null
field: 73746a98-f3e9-44a0-865e-736bbe7ee377 # Actions
fieldLayouts:
  c001836d-c171-4e57-81a9-ff76b77e3998:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 599e0f23-292c-45fe-850b-ab298e84558c # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33b4c03a-8a77-44b1-9188-6be247e6f3a7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ad293fae-50be-4dd6-81da-6bbfb16d92da # Action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6363579e-6a77-4a19-9f3e-564943b20c65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 701e9518-a15c-4199-b392-b0c7c4b6767e # Action Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 759f06c1-649d-43b0-82a8-b680cb1c0364
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 66155a4a-6429-42f8-ae4f-0fdc402bd3ba
        userCondition: null
fields:
  599e0f23-292c-45fe-850b-ab298e84558c: # Icon
    columnSuffix: bjvtvpgk
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: null
    name: Icon
    searchable: false
    settings:
      sets:
        - UI-profile
    translationKeyFormat: null
    translationMethod: none
    type: modules\ccfieldsmodule\fields\Icon
  701e9518-a15c-4199-b392-b0c7c4b6767e: # Action Text
    columnSuffix: mvrzjrwe
    contentColumnType: text
    fieldGroup: null
    handle: actionText
    instructions: 'Use this field to override the selected action text.'
    name: 'Action Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ad293fae-50be-4dd6-81da-6bbfb16d92da: # Action
    columnSuffix: sfjtuxev
    contentColumnType: string
    fieldGroup: null
    handle: action
    instructions: null
    name: Action
    searchable: false
    settings:
      newLabelFormat: '{{ label }}'
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - none
        -
          __assoc__:
            -
              - label
              - 'Deactivate Account'
            -
              - value
              - deactivateAccount
        -
          __assoc__:
            -
              - label
              - 'Delete Account'
            -
              - value
              - deleteAccount
        -
          __assoc__:
            -
              - label
              - 'Reset Password'
            -
              - value
              - resetPassword
      sourceGlobal: accountActions
      sourceLabelHandle: label
      sourceValueHandle: value
    translationKeyFormat: null
    translationMethod: none
    type: modules\ccfieldsmodule\fields\PresetDropdown
