changedFieldIndicator: 1835979850
field: 695e9090-0c77-43d1-b268-235e729bea6c # Questions
fieldLayouts:
  8196f677-ef50-4570-a148-223d189fac08:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dbd38305-efbf-44e4-b014-611692891afe # Question
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 079a540a-36cc-4a8c-86e9-a13259b0665b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7cfbb76c-d4ca-495d-895a-2e3910ea3606 # Answer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5edcbdf-f1e0-4070-9193-df856f55bb86
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 05dbbc3d-2ff8-47bb-a185-456948190c1a
        userCondition: null
fields:
  7cfbb76c-d4ca-495d-895a-2e3910ea3606: # Answer
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: answer
    instructions: 'Use this field to add the related answer.'
    name: Answer
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dbd38305-efbf-44e4-b014-611692891afe: # Question
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: question
    instructions: 'Use this field to add the question.'
    name: Question
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
