changedFieldIndicator: 170643775
field: 4c6ba5dd-7eca-49fc-9f60-b4943c7676a9 # Features
fieldLayouts:
  446e690d-4ff2-4310-b465-3fd3a3fb6e0e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b2b6f79d-8b07-48d1-bb98-31babebc41c0 # Feature Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 627730f8-4046-446f-9efc-6ca854d6d387
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b667cf4e-8b2f-4552-8a24-f4ac16cb0ca1 # Feature Columns
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf8f6410-c66f-4800-ac59-dc035f1c8c87
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c85e0203-5ac0-48eb-a547-18f54b60326a
        userCondition: null
fields:
  b2b6f79d-8b07-48d1-bb98-31babebc41c0: # Feature Name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: featureName
    instructions: 'Use this field to add the feature name. This will display as the heading for the row.'
    name: 'Feature Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b667cf4e-8b2f-4552-8a24-f4ac16cb0ca1: # Feature Columns
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: featureColumns
    instructions: 'Use this field to add columns to this module. The order of the columns should match the order in the Column Headings field.'
    name: 'Feature Columns'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Checked
                -
                  - handle
                  - checked
                -
                  - width
                  - 100px
                -
                  - type
                  - lightswitch
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - 'Column Text'
                -
                  - handle
                  - columnText
                -
                  - width
                  - ''
                -
                  - type
                  - multiline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
