fieldLayouts:
  d8956a91-c3e6-4323-93a1-5eaebcaecfd4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a761c7d6-6827-4eb0-999d-173f8ad256af # Alert Banner
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0eab6ce6-8580-475f-826b-44c2347f505d
            userCondition: null
            warning: null
            width: 100
        name: 'Alert Banner'
        uid: 1682e09a-cea7-42d5-80ab-66e85fca2d4d
        userCondition: null
handle: alerts
name: Alerts
sortOrder: 1
