fieldLayouts:
  38085600-15a5-4fc1-b15e-dcc4efa558bb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 96ae9512-2817-4b13-8656-2f8a7cce93bc # Copyright Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfc8447f-6e45-483b-9919-84546429d002
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 92c539c5-e961-4fb3-b1d2-6d221805330c # Disclaimer Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d68e389-f25a-4e64-8911-60d85c62b238
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e892298c-0e56-492b-b94d-134ff89c90ae # Payment Icons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c3a9cd5-26d3-4df8-a5cd-28b48f55825f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9c9597bc-756e-4cbd-a7d8-32b2d1cbba25
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
