defaultPlacement: end
enableVersioning: true
handle: author
name: Author
propagationMethod: all
siteSettings:
  da016506-9b96-43e4-9e38-d4c30ec3294c: # Olina
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
