defaultPlacement: end
enableVersioning: true
handle: order
name: Order
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '/_preview/order/{{canonicalId}}/{{id}}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  da016506-9b96-43e4-9e38-d4c30ec3294c: # Olina
    enabledByDefault: true
    hasUrls: true
    template: checkout/_order.twig
    uriFormat: '{slug}'
type: single
