defaultPlacement: end
enableVersioning: true
handle: page
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  da016506-9b96-43e4-9e38-d4c30ec3294c: # Olina
    enabledByDefault: true
    hasUrls: true
    template: entries/_page.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 8315e780-c8a9-4548-851b-3bcd38d6dc73
type: structure
