tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 76ab05df-5769-47cf-8362-1fb5a050981e
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        elementCondition: null
        id: null
        instructions: null
        label: null
        orientation: null
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: 28406238-fd3d-4b44-b175-0941444ac2de
        userCondition: null
        warning: null
        width: 100
      -
        attribute: fullName
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\FullNameField
        uid: a57461c1-4db5-4ba0-88e2-139c7e74c503
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 3408c3d5-b152-4c76-ac68-2129cfe14980
        userCondition: null
        warning: null
      -
        elementCondition: null
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\commerce\fieldlayoutelements\UserAddressSettings
        uid: 0fc5580e-2b53-4fde-a9dd-66a34dc21e4b
        userCondition: null
        warning: null
    name: Content
    uid: 497b56c2-a2c3-49c1-9098-8c4625a16869
    userCondition: null
